### ISSUE TITLE
Community is hanging

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/community.elgg.org#1]
Something is causing timeouts on the community.
I get: The page you are looking for is temporarily unavailable.
Please try again later.

**Comment by Srokap** [comment]
That's due to a scan running currently. I'm looking at it now and trying to figure out what's maxing out. It doesn't seem to be any obvious bottleneck.

**Comment by Srokap** [comment]
I reconfigured it to better handle increased load. It should be much more responsive under stress now. Still monitoring it after changes though.

**Comment by ewinslow** [comment]
What did you change?

**Comment by Srokap** [comment]
Details went into internal email. Basically we had error in nginx requests handling as well as we were badly handling long requests that are being artificially created by registration randomizer and were filling up workers pool which is now extended significantly.

Edit: Additionally have a look at: https://github.com/brettp/elgg-registration-randomizer/pull/2 that removes unnecessary registration randomizer resources usage.
