### ISSUE TITLE
plusone.js on the community site

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/community.elgg.org#2]
I have installed a cookie tracking extension to get a better understanding of what's happening with cookies and trackers on various sites, and it seems that the community site is loading plusone.js from Google. I don't recall seeing the actual 1+ button anywhere. Is it loaded with Google Analytics? Or is there some leftover ode?

**Comment by Srokap** [comment]
It probably comes from Evan's Google Tools which we use for google analytics as far as I can tell now.

If that's the case, I'd say that's a non-issue really.

/cc @ewinslow

**Comment by ewinslow** [comment]
Correct
